// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Pgvector;
using Rag.Infrastructure.Persistence;

#nullable disable

namespace Rag.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RagDbContext))]
    [Migration("20260723181841_InitialPersistence")]
    partial class InitialPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rag.Domain.Entities.Chatbot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("KnowledgeBaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("knowledge_base_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_chatbots");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_chatbots_tenant_id_id");

                    b.HasIndex("TenantId", "KnowledgeBaseId");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_chatbots_tenant_name");

                    b.ToTable("chatbots", (string)null);
                });

            modelBuilder.Entity("Rag.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("character(64)")
                        .HasColumnName("content_hash");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("KnowledgeBaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("knowledge_base_id");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StorageObjectKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("storage_object_key");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("version_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.HasAlternateKey("TenantId", "KnowledgeBaseId", "VersionId", "Id")
                        .HasName("ak_documents_scope_id");

                    b.HasIndex("VersionId", "ContentHash")
                        .IsUnique()
                        .HasDatabaseName("ux_documents_version_hash");

                    b.HasIndex("TenantId", "KnowledgeBaseId", "VersionId")
                        .HasDatabaseName("ix_documents_scope");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("Rag.Domain.Entities.DocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("character(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<Guid>("KnowledgeBaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("knowledge_base_id");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("to_tsvector('simple'::regconfig, coalesce(content, ''::text))", true);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TokenCount")
                        .HasColumnType("integer")
                        .HasColumnName("token_count");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("version_id");

                    b.HasKey("Id")
                        .HasName("pk_document_chunks");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_document_chunks_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("TenantId", "KnowledgeBaseId", "VersionId")
                        .HasDatabaseName("ix_document_chunks_scope");

                    b.HasIndex("VersionId", "DocumentId", "ChunkIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_document_chunks_position");

                    b.HasIndex("VersionId", "DocumentId", "ContentHash")
                        .IsUnique()
                        .HasDatabaseName("ux_document_chunks_hash");

                    b.HasIndex("TenantId", "KnowledgeBaseId", "VersionId", "DocumentId");

                    b.ToTable("document_chunks", (string)null);
                });

            modelBuilder.Entity("Rag.Domain.Entities.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operation");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasColumnType("character(64)")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponseBodyJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_body");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_status_code");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_idempotency_records");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_idempotency_records_expires_at");

                    b.HasIndex("TenantId", "Operation", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_idempotency_records_key");

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("Rag.Domain.Entities.IngestionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Guid>("KnowledgeBaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("knowledge_base_id");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<Guid?>("LockToken")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_token");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("version_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_ingestion_jobs");

                    b.HasIndex("Status", "AvailableAt")
                        .HasDatabaseName("ix_ingestion_jobs_dequeue");

                    b.HasIndex("TenantId", "KnowledgeBaseId", "VersionId")
                        .HasDatabaseName("ix_ingestion_jobs_scope");

                    b.HasIndex("TenantId", "KnowledgeBaseId", "VersionId", "DocumentId");

                    b.ToTable("ingestion_jobs", (string)null);
                });

            modelBuilder.Entity("Rag.Domain.Entities.KnowledgeBase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_bases");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_knowledge_bases_tenant_id_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_knowledge_bases_tenant_name");

                    b.ToTable("knowledge_bases", (string)null);
                });

            modelBuilder.Entity("Rag.Domain.Entities.KnowledgeBaseVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EmbeddingDimensions")
                        .HasColumnType("integer")
                        .HasColumnName("embedding_dimensions");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("embedding_model");

                    b.Property<Guid>("KnowledgeBaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("knowledge_base_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_base_versions");

                    b.HasAlternateKey("TenantId", "KnowledgeBaseId", "Id")
                        .HasName("ak_kb_versions_scope_id");

                    b.HasIndex("TenantId", "KnowledgeBaseId")
                        .HasDatabaseName("ix_kb_versions_scope");

                    b.HasIndex("TenantId", "KnowledgeBaseId", "Status")
                        .IsUnique()
                        .HasDatabaseName("ux_kb_versions_one_active")
                        .HasFilter("status = 'Active'");

                    b.ToTable("knowledge_base_versions", (string)null);
                });

            modelBuilder.Entity("Rag.Domain.Entities.QueryLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ChatbotId")
                        .HasColumnType("uuid")
                        .HasColumnName("chatbot_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Degraded")
                        .HasColumnType("boolean")
                        .HasColumnName("degraded");

                    b.Property<int>("DurationMilliseconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<Guid>("KnowledgeBaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("knowledge_base_id");

                    b.Property<string>("QueryHash")
                        .IsRequired()
                        .HasColumnType("character(64)")
                        .HasColumnName("query_hash");

                    b.Property<int>("ResultCount")
                        .HasColumnType("integer")
                        .HasColumnName("result_count");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("version_id");

                    b.HasKey("Id")
                        .HasName("pk_query_logs");

                    b.HasIndex("TenantId", "ChatbotId");

                    b.HasIndex("TenantId", "KnowledgeBaseId", "VersionId", "CreatedAt")
                        .HasDatabaseName("ix_query_logs_scope_created");

                    b.ToTable("query_logs", (string)null);
                });

            modelBuilder.Entity("Rag.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Rag.Domain.Entities.Chatbot", b =>
                {
                    b.HasOne("Rag.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_chatbots_tenants");

                    b.HasOne("Rag.Domain.Entities.KnowledgeBase", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "KnowledgeBaseId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_chatbots_knowledge_bases");
                });

            modelBuilder.Entity("Rag.Domain.Entities.Document", b =>
                {
                    b.HasOne("Rag.Domain.Entities.KnowledgeBaseVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "KnowledgeBaseId", "VersionId")
                        .HasPrincipalKey("TenantId", "KnowledgeBaseId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_documents_kb_versions");
                });

            modelBuilder.Entity("Rag.Domain.Entities.DocumentChunk", b =>
                {
                    b.HasOne("Rag.Domain.Entities.Document", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "KnowledgeBaseId", "VersionId", "DocumentId")
                        .HasPrincipalKey("TenantId", "KnowledgeBaseId", "VersionId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_document_chunks_documents");
                });

            modelBuilder.Entity("Rag.Domain.Entities.IdempotencyRecord", b =>
                {
                    b.HasOne("Rag.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_idempotency_records_tenants");
                });

            modelBuilder.Entity("Rag.Domain.Entities.IngestionJob", b =>
                {
                    b.HasOne("Rag.Domain.Entities.Document", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "KnowledgeBaseId", "VersionId", "DocumentId")
                        .HasPrincipalKey("TenantId", "KnowledgeBaseId", "VersionId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ingestion_jobs_documents");
                });

            modelBuilder.Entity("Rag.Domain.Entities.KnowledgeBase", b =>
                {
                    b.HasOne("Rag.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_knowledge_bases_tenants");
                });

            modelBuilder.Entity("Rag.Domain.Entities.KnowledgeBaseVersion", b =>
                {
                    b.HasOne("Rag.Domain.Entities.KnowledgeBase", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "KnowledgeBaseId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_kb_versions_knowledge_bases");
                });

            modelBuilder.Entity("Rag.Domain.Entities.QueryLog", b =>
                {
                    b.HasOne("Rag.Domain.Entities.Chatbot", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ChatbotId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_query_logs_chatbots");

                    b.HasOne("Rag.Domain.Entities.KnowledgeBaseVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "KnowledgeBaseId", "VersionId")
                        .HasPrincipalKey("TenantId", "KnowledgeBaseId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_query_logs_kb_versions");
                });
#pragma warning restore 612, 618
        }
    }
}
